#!/usr/bin/env crystal

# Convert Rust bidi_class_table from vendor/unicode-bidi/src/char_data/tables.rs
# to Crystal format for src/bidi/char_data/tables_data.cr

require "file_utils"

def convert_rust_table_to_crystal(input_path : String, output_path : String)
  puts "Converting Rust table from #{input_path} to Crystal #{output_path}"

  content = File.read(input_path)

  # Find the bidi_class_table definition
  table_start = content.index("pub const bidi_class_table: &'static [(char, char, BidiClass)] = &[")
  return unless table_start

  table_start = content.index('[', table_start).not_nil! + 1
  table_end = content.index(']', table_start).not_nil!
  table_content = content[table_start...table_end]

  # Parse the Rust table entries
  entries = [] of Tuple(String, String, String)

  # Split by commas, but be careful with nested tuples
  current_entry = ""
  paren_depth = 0
  table_content.each_char do |ch|
    case ch
    when '('
      paren_depth += 1
      current_entry += ch if paren_depth > 1
    when ')'
      if paren_depth == 1
        # End of entry
        entry_str = current_entry.strip
        if !entry_str.empty?
          # Parse entry like ('\u{0}', '\u{8}', BN)
          if match = entry_str.match(/'\u\{([0-9a-f]+)\}',\s*'\u\{([0-9a-f]+)\}',\s*(\w+)/)
            lo = "\\u{#{match[1]}}"
            hi = "\\u{#{match[2]}}"
            cls = match[3]
            entries << {lo, hi, cls}
          end
        end
        current_entry = ""
      else
        current_entry += ch
      end
      paren_depth -= 1
    when ','
      if paren_depth == 0
        # Between entries, ignore
      else
        current_entry += ch
      end
    else
      current_entry += ch if paren_depth > 0
    end
  end

  puts "Found #{entries.size} entries"

  # Generate Crystal output
  output = <<-CRYSTAL
# NOTE:
# The following code was generated by "tools/convert_rust_table.cr" from
# vendor/unicode-bidi/src/char_data/tables.rs
# Do not edit directly.

module Bidi
  module CharData
    BIDI_CLASS_TABLE = [
  CRYSTAL

  # Format entries
  entries.each_with_index do |(lo, hi, cls), i|
    crystal_cls = "BidiClass::#{cls}"
    entry = "      {'#{lo}', '#{hi}', #{crystal_cls}}"
    entry += "," unless i == entries.size - 1
    output += entry + "\n"
  end

  output += <<-CRYSTAL
    ]
  end
end
  CRYSTAL

  # Write output
  File.write(output_path, output)
  puts "Written to #{output_path}"
end

# Run conversion
if ARGV.size >= 2
  convert_rust_table_to_crystal(ARGV[0], ARGV[1])
else
  rust_path = File.join(__DIR__, "..", "vendor", "unicode-bidi", "src", "char_data", "tables.rs")
  crystal_path = File.join(__DIR__, "..", "src", "bidi", "char_data", "tables_data.cr")
  convert_rust_table_to_crystal(rust_path, crystal_path)
end